name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set and install dependencies
      run: sudo apt-get install libboost-all-dev cmake
    - name: configure
      run: mkdir build && cd build && cmake -DWITH_INTEGER=ON ..
    - name: make
      run: cd build && make
    - name: run
      run: pwd && sudo chmod +x command.sh && ./command.sh
