name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set and install dependencies
      run: sudo apt-get install libboost-all-dev cmake
    - name: configure
      run: mkdir build && cd build && cmake -DWITH_INTEGER=ON ..
    - name: make
      run: cd build && make
    - name: make check
      run: pwd && ./build/bin/rcv_int 127.0.0.1 1234 & ; ./build/bin/sender_int 127.0.0.1 1234 7
    - name: make distcheck
      run: make distcheck
